---
- name: Install pycurl
  hosts: dockerhosts
  sudo: yes
  gather_facts: no
  tasks:
    - name: Install pycurl
      apt: pkg=python-pycurl update_cache=yes cache_valid_time=600

- name: Install Docker 
  hosts: dockerhosts
  sudo: yes
  roles:
      - angstwad.docker_ubuntu

- name: Firewall
  hosts: dockerhosts
  sudo: yes
  tasks:
    - name: Enable Firewall 
      ufw: state=enabled policy=deny
    - name: Allow OpenSSH
      ufw: rule=allow name=OpenSSH

